disabled_rules:
  - implicit_getter
  - todo
  - type_body_length
  - file_length
  # rules to be enabled
  - no_space_in_method_call

opt_in_rules:
  - array_init
  - closure_end_indentation
  - closure_spacing
  - collection_alignment
  - contains_over_filter_is_empty
  - contains_over_first_not_nil
  - contains_over_range_nil_comparison
  - convenience_type
  - empty_collection_literal
  - empty_count
  - empty_string
  - enum_case_associated_values_count
  - explicit_init
  - explicit_top_level_acl
  - extension_access_modifier
  - fallthrough
  - fatal_error_message
  - file_name_no_space
  - first_where
  - function_default_parameter_at_end
  - identical_operands
  - joined_default_parameter
  - last_where
  - legacy_random
  - let_var_whitespace
  - literal_expression_end_indentation
  - modifier_order
  - multiline_arguments
  - multiline_function_chains
  - multiline_parameters
  - nimble_operator
  - nslocalizedstring_key
  - number_separator
  - overridden_super_call
  - override_in_extension
  - prefer_self_type_over_type_of_self
  - private_action
  - private_outlet
  - redundant_nil_coalescing
  - redundant_objc_attribute
  - redundant_type_annotation
  - required_enum_case
  - sorted_first_last
  - static_operator
  - strong_iboutlet
  - switch_case_on_newline
  - toggle_bool
  - unavailable_function
  - unneeded_parentheses_in_closure_argument
  - unowned_variable_capture
  - vertical_parameter_alignment_on_call
  - vertical_whitespace
  - vertical_whitespace_between_cases
  - vertical_whitespace_closing_braces
  - vertical_whitespace_opening_braces
  # rules to be enabled
  # - closure_body_length
  # - file_types_order
  # - force_unwrapping
  # - indentation_width
  # - type_contents_order
  # - untyped_error_in_catch
  # access modifier rules to resolve
  # - explicit_acl
  # - lower_acl_than_parent
  # - no_extension_access_modifier

analyzer_rules: 
  - unused_declaration
  - unused_import

excluded:
  - .swiftpm
  - .build

# rule configuration
cyclomatic_complexity: 12

identifier_name:
  excluded: ["_", "i", "j", "v", "dx", "dy", "id", "up", "on", "off"]

line_length: 200

type_name: 
  max_length: 50
